### ISSUE TITLE
test_get_productions()

### ISSUE THREAD

**Issue by qsong4** [iit-cs585/assignments#3]
Im still confuse about test function test_get_productions()
        self.assertEqual(productions[0], ('S', ['NP', 'VP']))
        self.assertEqual(productions[1], ('NP', ['N']))
        self.assertEqual(productions[2], ('N', ['John']))
        self.assertEqual(productions[3], ('VP', ['V', 'N']))
        self.assertEqual(productions[4], ('V', ['books']))
        self.assertEqual(productions[5], ('N', ['flight']))
Depend on the test case we know that the left side of list is the top of stack, so we need to sort the list ['NP', 'VP'] then we can make 'NP' at the top of stack. But at this case self.assertEqual(productions[3], ('VP', ['V', 'N'])) 'V' is at left side of 'N', so I can not pass the test case. I think there is something wrong about test case. Hope I clearly express my situation...

**Comment by qsong4** [comment]
Anyone pass the test case of this function, please help!

**Comment by aronwc** [comment]
@qsong4 Sorry, I don't quite understand your question.

The purpose of get_productions is to list the CFG rules that are used to produce the given tree. 
The order in which the rules are returned is depth-first, left-to-right.

For the example in the test case, the first rule is S->NP VP. Then, we expand the NP rule, since it is the left most constituent that has not been expanded. This leads to N -> John.
There should not be a need to sort any of the right-hand-sides of any rule.

You may find recursion helpful for completing this function.

Hope that helps,
Aron

**Comment by qsong4** [comment]
@aronwc Because this tree structure does not have left and right, we can not control what on the left without sorting. For example, the first rule is S->VP NP without sorting, but after sorting the fourth rule become VP-> N V which does not satisfy the test case. Hope I make myself clear this time :)

I am gonna  try recursion, maybe it will not have this problem.

**Comment by karthikshivaram24** [comment]
I'm facing a similar problem , instead of the order defined in the test case as:

1. ('S', ['NP', 'VP'])
2. ('NP', ['N'])
3. ('N', ['John'])
4. ('VP', ['V', 'N'])
5. ('V', ['books'])
6. ('N', ['flight'])

I am getting the output in the following order:

1. ('S', ['NP', 'VP'])
2. ('NP', ['N'])
3. ('VP', ['V', 'N'])
4. ('N', ['John'])
5. ('V', ['books'])
6. ('N', ['flight'])

The order of  ('N', ['John']) and  ('VP', ['V', 'N']) are getting interchanged.
Is this output valid or is there something wrong in my function .

**Comment by karthikshivaram24** [comment]
Figured it out , implemented breadth first search by mistake.

**Comment by qsong4** [comment]
Karthik Shivaram <notifications@github.com>于2017年1月22日 周日下午3:40写道：

**Comment by karthikshivaram24** [comment]
I had used a deque by mistake without noticing it was BFS logic, then i tried with a stack but still output would not match due to the order of the nodes entering the stack, hence i used recursion as Professor suggested , it is working now.

**Comment by qsong4** [comment]
Karthik Shivaram <notifications@github.com>于2017年1月22日 周日下午7:37写道：
